spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
  data:
    rest:
      base-path: /api
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate-drop-unused
      contact-points:
      - 127.0.0.1:9042
      local-datacenter: datacenter1
  main:
    allow-bean-definition-overriding: true
tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-username
    password: tacopass
    poll-rate: 10000
  api:
    url: http://api.tacocloud.com