spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
  data:
    rest:
      base-path: /api
tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-username
    password: tacopass
    poll-rate: 10000
  api:
    url: http://api.tacocloud.com